# Generated by Django 4.1 on 2022-08-31 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('age', models.IntegerField(max_length=2, verbose_name='Возраст')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('number', models.IntegerField(verbose_name='Номер телефона')),
            ],
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'Контент', 'verbose_name_plural': 'Контент'},
        ),
    ]
